/* If you're feeling fancy you can add interactivity 
    to your site with Javascript */
function wait(time) {
return new Promise(resolve => {
setTimeout(() => {
resolve();
}, time);
});
}
async function testWait() {
await wait(5000);
}
console.log("Connection the theyardbros.glitch.me from line 21 on PyServ Initiated.");
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request Rate limit reached. Please wait.")
testWait()
console.log("Requests are allowed now.")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request denied")
console.log("Request accepted.")
console.log("AAVPR ROTO SANS () {!Signatures!}")
console.log("Constant Website Query has Started.")
while (true) {
  console.log("Query sent")
  console.log("Query accepted")
}
